#!/usr/bin/env bash

# This file generates a recursive hash of a directory.

set -o nounset
set -o errexit
set -o pipefail
# set -o xtrace

# Global variables.

declare VERBOSE=false
declare -a ROOTPATHS=()

function parse_options() {
  while (( "$#" )); do
    case "$1" in
      -v|--verbose)
        VERBOSE=true
        shift
        ;;
      --) # end argument parsing
        shift
        break
        ;;
      -*|--*=) # unsupported flags
        echo "Error: Unsupported flag $1" >&2
        exit 1
        ;;
      *) # preserve positional arguments
        ROOTPATHS+=("$1")
        shift
        ;;
    esac
  done

  ROOTPATHS+=("$@")

  if [[ "$VERBOSE" = true ]]; then
    printf 'INFO Rootpaths:\n' >&2
    printf 'INFO - %s\n' "${ROOTPATHS[@]-(none)}" >&2
  fi
}

function main() {
  parse_options "$@"

  if [ "${#ROOTPATHS[@]}" -eq 0 ]; then
    return 0;
  fi

  local cmd=(find . -type f -exec shasum {} +)

  if [[ "$VERBOSE" = true ]]; then
    printf 'INFO Command: ' >&2
    printf '%s ' "${cmd[@]}" >&2
    printf '\n' >&2
  fi

  pwd=$(pwd)

  for rootpath in "${ROOTPATHS[@]}"; do
    cd "$rootpath"

    "${cmd[@]}" | sort -k 2

    cd "$pwd"
  done
}

main "$@"
