#!/usr/bin/env bash

# This file generates a recursive hash of a directory.

set -o nounset
set -o errexit
set -o pipefail
# set -o xtrace

# Global variables.

declare -a EXCLUDES=()
declare VERBOSE=false
declare -a ROOTPATHS=()

function parse_options() {
  while (( "$#" )); do
    case "$1" in
      -v|--verbose)
        VERBOSE=true
        shift
        ;;
      -e|--exclude)
        EXCLUDES+=("$2")
        shift 2
        ;;
      --) # end argument parsing
        shift
        break
        ;;
      -*|--*=) # unsupported flags
        echo "Error: Unsupported flag $1" >&2
        exit 1
        ;;
      *) # preserve positional arguments
        ROOTPATHS+=("$1")
        shift
        ;;
    esac
  done

  ROOTPATHS+=("$@")

  if [[ "$VERBOSE" = true ]]; then
    printf 'INFO Excludes:\n' >&2
    printf 'INFO - %s\n' "${EXCLUDES[@]-(none)}" >&2
    printf 'INFO Rootpaths:\n' >&2
    printf 'INFO - %s\n' "${ROOTPATHS[@]-(none)}" >&2
  fi
}

function process() {
  local path
  path="$1"

  if [[ -f "$path" ]]; then
    if [[ "$VERBOSE" = true ]]; then
      printf 'INFO Processing file %s\n' "$path" >&2
    fi

    shasum "$path"
  elif [[ -d "$path" ]]; then
    if [[ "$VERBOSE" = true ]]; then
      printf 'INFO Processing directory %s\n' "$path" >&2
    fi

    printf 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  %s\n' "$path"
  else
    if [[ "$VERBOSE" = true ]]; then
      printf 'INFO Skipping unknown node %s\n' "$path" >&2
    fi
  fi
}

export -f process

function main() {
  parse_options "$@"

  if [ "${#ROOTPATHS[@]}" -eq 0 ]; then
    return 0;
  fi

  local cmd=(find .)

  if [ "${#EXCLUDES[@]}" -ne 0 ]; then
    for exclude in "${EXCLUDES[@]}"; do
      cmd+=(\( -name "${exclude}" -prune \) -or)
    done
  fi

  cmd+=(-exec bash -c 'process "$@"' bash {} \;)

  if [[ "$VERBOSE" = true ]]; then
    printf 'INFO Command: ' >&2
    printf '%s ' "${cmd[@]}" >&2
    printf '\n' >&2
  fi

  pwd=$(pwd)

  for rootpath in "${ROOTPATHS[@]}"; do
    cd "$rootpath"

    "${cmd[@]}" | LC_ALL=C sort -k 2

    cd "$pwd"
  done
}

main "$@"
